default_stages: [commit]
fail_fast: false
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/asottile/blacken-docs
    rev: main
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: main
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pycqa/flake8
    rev: main
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]